## 사이킷런(scikit-learn) 설치

In [1]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
#버전 확인
import sklearn

print(sklearn.__version__)

1.0.2


## 붓꽃 분류 모델 만들기

In [3]:
#붓꽃데이터 불러오기
from sklearn.datasets import load_iris
#분류 모델 불러오기
from sklearn.tree import DecisionTreeClassifier
#데이터셋 분류 라이브러리
from sklearn.model_selection import train_test_split

In [5]:
#피처들과 데이터 값을 DataFrame으로 변한하기 위함
import pandas as pd

#붓꽃 데이터 세트 로딩
iris = load_iris()

#iris.data는 Iris 데이터 세트에서 피처(Feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
print("iris target 값 :", iris_label)
print("iris target 명 :", iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다.
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 : ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [6]:
#데이터를 학습, 테스트로 나누어 줍니다.
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

In [7]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[5.1 3.5 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [7.7 2.8 6.7 2. ]
 [5.  3.3 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [7.6 3.  6.6 2.1]
 [6.7 3.  5.  1.7]
 [5.5 3.5 1.3 0.2]
 [6.  2.7 5.1 1.6]
 [5.  2.  3.5 1. ]
 [7.9 3.8 6.4 2. ]
 [4.6 3.4 1.4 0.3]
 [6.9 3.1 4.9 1.5]
 [6.5 3.  5.8 2.2]
 [5.1 2.5 3.  1.1]
 [6.6 2.9 4.6 1.3]
 [5.  3.2 1.2 0.2]
 [7.4 2.8 6.1 1.9]
 [5.1 3.8 1.6 0.2]
 [6.8 3.2 5.9 2.3]
 [6.9 3.1 5.1 2.3]
 [5.9 3.  4.2 1.5]
 [4.9 2.5 4.5 1.7]
 [6.7 3.1 4.7 1.5]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.7 0.2]
 [6.5 2.8 4.6 1.5]
 [5.1 3.7 1.5 0.4]
 [5.  3.4 1.6 0.4]
 [6.1 2.6 5.6 1.4]
 [6.5 3.  5.5 1.8]
 [6.3 2.5 5.  1.9]
 [5.2 3.4 1.4 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [6.1 2.8 4.7 1.2]
 [5.1 3.4 1.5 0.2]
 [5.6 3.  4.1 1.3]
 [6.3 2.7 4.9 1.8]
 [7.1 3.  5.9 2.1]
 [5.5 2.6 4.4 1.2]
 [5.  2.3 3.3 1. ]
 [6.3 3.4 5.6 2.4]
 [5.8 2.7 5.1 1.9]
 [5.5 4.2 1.4 0.2]
 [5.6 2.7 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [6.7 2.5 5.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.7 3.1 5.6 2.4]
 [4.6 3.2 1.4 0.2]
 [7.7 3.8 6.

##학습 및 결과 예측

In [9]:
#DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state = 11)

#학습 수행
dt_clf.fit(X_train, y_train)

#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

#실제 정확도 측정
from sklearn.metrics import accuracy_score
print('예측 정확도 : %.4f' %accuracy_score(y_test, pred))

예측 정확도 : 0.9333
